version: "3.7"

networks:
  phpdev:

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    volumes: 
        - ./code:/var/www/html
        - ./logs:/var/log/nginx
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites-available:/etc/nginx/sites-available
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - phpdev

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./code:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - phpdev

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - /code:/var/www/html
    working_dir: /var/www/html
    networks:
      - phpdev

