version: "3.7"

networks:
  laravel:

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    volumes: 
        - ./code:/var/www/html
        - ./logs:/var/log/nginx
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "8080:80"
    networks:
      - laravel

